apiVersion: v1
kind: Service
metadata:
  name: capstone-app-service
  namespace: capstone
  labels:
    app: capstone-app
    project: capstone
spec:
  type: NodePort
  selector:
    app: capstone-app
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080